### ISSUE TITLE
package_data not included in .deb

### ISSUE THREAD

**Issue by lamby** [spotify/dh-virtualenv#119]
Somewhat of a duplicate of #113 but I have a minimal testcase that I believe should Just Work. Or I have incorrect assumptions and thus we need some documentation that puts this issue finally to bed.

To reproduce:

    $ sudo apt-get install build-essential debhelper python dh-virtualenv 
    $ cd $(mktemp -d)
    $ wget http://lamby.uwcs.co.uk/b/dh-virtualenv-testcase.tar.gz
    $ tar xvfz dh-virtualenv-testcase.tar.gz
    $ cd dh-virtualenv-testcase-1/
    $ dpkg-buildpackage -uc -us -rfakeroot
    $ dpkg -c ../dh-virtualenv-testcase_1_amd64.deb | grep package_data

Expected: seeing `package_data/testcase.txt` in the list of files.

(Perhaps we need some documentation anyway; we don't seem to be clear whether we are building *Python* source packages ie. sdist/MANIFEST or purely binary ones.)

**Comment by jhermann** [comment]
This has nothing to do with dh-virtualenv really, since your sdist and egg/wheel files are missing what you want to have in them, too. That the .deb doesn't have them either is a mere consequence.

You have data, not package data (package data lives in a package dir, yours does not). So either `mv package_data dh_virtualenv_testcase/data` and `include_package_data=True`, or…

    setup(
        name='dh-virtualenv-testcase',
        packages=find_packages(),
        zip_safe=False,
        data_files=[('testcase-data', ['package_data/testcase.txt'])],
    )

Also:

    $ cat MANIFEST.in 
    graft package_data

Having data files used in/by the code as actual package data is the better way, and writing that code in a zip_safe way is good style.

**Comment by nailor** [comment]
Closing this since it is not an issue in the project. Thanks @jhermann for looking into this!

**Comment by lamby** [comment]
No problem and thank you for explaining. Works great :) 

(data_files seems a better fit for Django projects as it turns out.)
