### ISSUE TITLE
Deb dependency chaining ?

### ISSUE THREAD

**Issue by asmodehn** [spotify/dh-virtualenv#133]
I am curious how to manage dependencies between packages built with dh_virtualenv.
This helped me a lot to get started : https://github.com/benjaminirving/python-debian-packaging-example but I couldn't find documentation about the dependencies topic... 

A usual python deb package can depend on another python deb package, since they are both on the machine environment. But : 
* Can a dh_venv built package depend on a usual python deb package ?
* Can a dh_venv built package depend on another dh_venv built package ? import modules from another venv ?
* Can a usual python deb package depend on a dh_venv built package ?

**Comment by asmodehn** [comment]
Here is what I m guessing so far : 

* Can a dh_venv built package depend on a usual python deb package ? YES : use the --with-site-packages when building your deb package
* Can a dh_venv built package depend on another dh_venv built package ? import modules from another venv ? NO ( venv are made to prevent that )
* Can a usual python deb package depend on a dh_venv built package ? NO (otherwise the previous case would likely be solved)

For NOs : Is there some workaround ? if not, is there something to prevent misuse by someone else of your dh_venv built package ?

Thanks for any tips.

**Comment by nailor** [comment]
For the second one you could maybe point the path to the other virtualenv's site-packages. Note though that this might have unforeseen consequences as you don't really know what libraries exist there.

Same would in theory work for the third option too, but it would probably have even more consequences. 

In any case, these would require some fiddling with `PYTHONPATH` when running processes and the integration would be far from seamless. Neither these features are also easy to support with virtualenvs (due to their nature), so I'm closing the ticket but hope the answer helps!

**Comment by asmodehn** [comment]
Thanks for the feedback.
I m thinking of releasing a dh_virtualenv build package into the wild wild web, so I was wondering what could be the potential consequences due to the package behaviors that users might not expect...
