### ISSUE TITLE
Problem with "Requirement already satisfied"

### ISSUE THREAD

**Issue by adi-** [spotify/dh-virtualenv#176]
When I build my project for 2nd, 3rd etc. time I get an error:

```
Processing /srv/test
  Requirement already satisfied (use --upgrade to upgrade): test==1.0.1 from file:///srv/test in /srv/test
```
I have found out the problem of not deleted `test.egg-info` folder. When I delete it manually and rebuild the package, everything is fine.

Is there any fix for that?

**Comment by adi-** [comment]
A fast workaround could be `--no-test` param, but that is not what really I am looking for.

Is there any chance that package build could delete all `egg-info` folders?

**Comment by nailor** [comment]
Hi,

in general I don't think it is the responsibility of the build tool to make sure the build environment is clean when the build starts. Deleting things like `egg-info` folders would also be quite scary. You never know if those are needed.

If you are not up to setting up a chrooted build environment or equivalent, I'd suggest adding deletion of those into the `debian/rules` file, either under the general `%:` or possibly adding an `override_dh_virtualenv` step.

Closing this issue since there's not much here dh-virtualenv can do here.

**Comment by jhermann** [comment]
The other thing that likely solves this is to use a sdist as the basis for the package build, instead of a polluted working directory. See here:

https://github.com/Springerle/dh-virtualenv-mold/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/rules#L29

**Comment by adi-** [comment]
@jhermann thanx for the link!
