### ISSUE TITLE
Options for a more compact deb?

### ISSUE THREAD

**Issue by mikepurvis** [spotify/dh-virtualenv#213]
For small utility-type packages, the end result can end up a bit bloated, especially by:

- The inclusion of the full Python binary.
- The inclusion of the pip and setuptools packages, which are not needed at runtime.

I'm able to successfully strip out pip and setuptools with the following in my rules file, and the packaged version of my tool continues to work correctly:

```
override_dh_builddeb:
  rm -r debian/<pkgname>/opt/venvs/*/lib/python2.7/site-packages/pip*
  rm -r debian/<pkgname>/opt/venvs/*/lib/python2.7/site-packages/setuptools*
  dh_builddeb
```

Unfortunately, if I swap out the bundled python executable for a link to the system one (using `dh_link`), it loses the context of the virtualenv and can no longer find the included packages.

It would be great if dh-virtualenv provided options to do some of this stuff out of the box.

**Comment by jhermann** [comment]
Regarding scripts, package up a  “standard” virtualenv, adding a named link to the virtualenv python into /usr/bin (debian/foo-base.links: opt/venvs/foo-base/bin/python usr/bin/foo-base-python).

Then you can make single packages of *.py files (using fpm) that depend on that base package, and use ``foo-base-python`` in their bang-path.

The base needs to be redeployed only if dependencies change, or for (security) updates.

**Comment by jhermann** [comment]
Regarding the cleanup, good idea, that could go into a ``--postremove`` option as a mirror to ``--preinstall``. But using the ‘official’ way, i.e. pip…

```sh
(suicide-is-painless) $ which pip
/home/jhe/tmp/suicide-is-painless/bin/pip
(suicide-is-painless) $ pip install -U pip setuptools wheel -q
(suicide-is-painless) $ pip uninstall -y pip setuptools wheel
Uninstalling pip-9.0.1:
  Successfully uninstalled pip-9.0.1
Uninstalling setuptools-35.0.2:
  Successfully uninstalled setuptools-35.0.2
Uninstalling wheel-0.29.0:
  Successfully uninstalled wheel-0.29.0
(suicide-is-painless) $ which pip
/home/jhe/.local/bin/pip
```

**Comment by mikepurvis** [comment]
I agree that a shared venv could work, but that's not what I want in this particular instance— I'd like to be able to generate one, and be able to opt out of 3+ MB of unneeded packages and Python binary.

Cleanup via pip sounds great! I wasn't sure if it would work for pip to uninstall itself, but obviously you demonstrate that it does.

I still don't understand why it didn't work to ship a symlink as `/opt/venvs/foo/bin/python` rather than the full binary.

**Comment by jhermann** [comment]
Because realpath is applied during bootstrapping the interpreter. If you wanna get rid of the binary, you have to rm it and add hardlinking code to the postinst script.

**Comment by mikepurvis** [comment]
Okay gross, definitely don't want that. My impression was that the default behaviour of `virtualenv` (without the `--always-copy` flag) was to symlink to the system versions. However, I see from testing it that the baseline `pythonx.y` binary seems to be always copied regardless.

```
$ virtualenv foo
New python executable in foo/bin/python2.7
Also creating executable in foo/bin/python
Installing setuptools, pip, wheel...done.
$ ls -la foo/bin
total 136
drwxr-xr-x  16 mikepurvis  staff    544 31 May 16:34 .
drwxr-xr-x   7 mikepurvis  staff    238 31 May 16:34 ..
-rw-r--r--   1 mikepurvis  staff   2080 31 May 16:34 activate
-rw-r--r--   1 mikepurvis  staff   1022 31 May 16:34 activate.csh
-rw-r--r--   1 mikepurvis  staff   2176 31 May 16:34 activate.fish
-rw-r--r--   1 mikepurvis  staff   1137 31 May 16:34 activate_this.py
-rwxr-xr-x   1 mikepurvis  staff    252 31 May 16:34 easy_install
-rwxr-xr-x   1 mikepurvis  staff    252 31 May 16:34 easy_install-2.7
-rwxr-xr-x   1 mikepurvis  staff    224 31 May 16:34 pip
-rwxr-xr-x   1 mikepurvis  staff    224 31 May 16:34 pip2
-rwxr-xr-x   1 mikepurvis  staff    224 31 May 16:34 pip2.7
lrwxr-xr-x   1 mikepurvis  staff      9 31 May 16:34 python -> python2.7
-rwxr-xr-x   1 mikepurvis  staff   2339 31 May 16:34 python-config
lrwxr-xr-x   1 mikepurvis  staff      9 31 May 16:34 python2 -> python2.7
-rwxr-xr-x   1 mikepurvis  staff  12568 31 May 16:34 python2.7
-rwxr-xr-x   1 mikepurvis  staff    231 31 May 16:34 wheel
```

With `--always-copy`, I get three additional copies of the interpreter here, rather than symlinks for `python` and `python2`.

**Comment by jhermann** [comment]
https://github.com/jhermann/devpi-enterprisey/blob/12bb50034390932fd8f345a89f3997d7026ae724/debianized-devpi/debian/rules#L61

Deleting tooling  is possible with a few extra lines in ``rules``, and a gain of roughly 10 MiB in installed size.

This is more of a docs/how-to topic though, because I doubt you can generally uninstall stuff just so (there must be at least an opt-out via ``--no-uninstall``). Note that you **can not** uninstall setuptools, since ``pkg_resources`` is often used at runtime.

**Comment by jhermann** [comment]
Finding candidates for custom deletion (i.e. per-app):

    /opt/venvs/devpi# du -h lib/* | sort -h

What you find is things like this:

    4,1M	lib/python3.5/site-packages/pyramid/tests

This is another argument for "do it in rules", since you cannot automate that, except if you restrict it to "well-known" packages.

**Comment by jhermann** [comment]
This should be flagged as a "documentation" issue.

**Comment by nailor** [comment]
Hm, I'm not entirely sure if I even want this to be included in documentation. I can see that in some cases. the binary sizes do matter, but for majority of cases they really don't, especially if the savings are in the ballpark of 10-or-so megabytes. 

Biggest flipside I can see is that if we write instructions on how to slim down the package, people are going to start doing that by default, thinking along the lines smaller == better, which then down the line could increase the support requests because of accidental deletion of something that was actually needed.

I'm closing this ticket for now, I think this ticket can hopefully be googleable enough to serve as a documentation to those struggling with too large binaries. Thanks a lot @jhermann for chiming in with lot of examples!
