### ISSUE TITLE
How to build both Python 2 and 3 packages?

### ISSUE THREAD

**Issue by sivachandran** [spotify/dh-virtualenv#341]
I'm able to build Python 2 or Python 3 packages by specifying interpreter through `--python` option. But I want to generate both versions of the package in single build. My `debian/control` has two binary packages, one for Python 2 and another one for Python 3. But how do I specify different values to `--python` option?

**Comment by nailor** [comment]
Hi,

Thanks for the question! Dh-virtualenv is not built for targeting multiple Python binaries, it’s rather meant to build a package that is deployable to a production system running the same interpreter as the build environment. 

However you should be able to achieve this using Debian’s native support for multi package builds, as we honour the package flag from dh.

Closing the issue since it is out of scope for the project
