### ISSUE TITLE
How to include config files?

### ISSUE THREAD

**Issue by codeinthehole** [spotify/dh-virtualenv#98]
I want to build a `.deb` file for a Django project that includes uWSGI and its config files. I'd like to include the uWSGI ini file in `/etc/uwsgi/package.ini` but can't get this working with `dh-virtualenv`. Please can you explain how to do this?

I've tried including it in `debian/etc/uwsgi/` but it doesn't install - I've also tried adding it to `debian/conffiles` and `debian/install` but without success. 

Apologies for the dumb question.

**Comment by jhermann** [comment]
See https://github.com/spotify/dh-virtualenv/blob/master/debian/dh-virtualenv.install for an example. Include the DEB package name in your descriptor files.

**Comment by codeinthehole** [comment]
That worked - thank you.

In case anyone else reads this, my package is called "helloworld" and I need to create a `debian/helloworld.install` with contents:
```
etc/uwsgi/helloworld.ini /etc/uwsgi/
```
I also needed to store the ini file in `etc/uwsgi/helloworld.ini` from the root of the project (not in the `debian/` folder as I was trying before).

**Comment by ipwaze** [comment]
David, as I ask myself the same questions only 5 years later.
Would You consider it an improvement to use [debian/conffiles](https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html#automatic-handling-of-configuration-files-by-dpkg) instead of debian/helloworld.install ? 

The helloworld.ini file would be put in the same directory, but then dpkg automatically manages local administrator decisions.

Cheers,
Florian

**Comment by jhermann** [comment]
anything in /etc is conffile by default / convention

**Comment by ipwaze** [comment]
hm... Jürgen I beleive we are not talking about the same thing. I know the LSB suggests You should put (most) configuration files in /etc. 
I cite the link I posted: "... conffiles. This file should be a list of filenames of configuration files **needing automatic handling**, separated by newlines." 

The next paragraph (5.2) talks about the respnsibilities You take on if You manage upgrading config files in maintainer scripts. 
My Question , to elaborate, is directed towards the **behaviour** of the package manager when putting this in "package".install  .

Is it better to put a config file in the debian/conffiles file to avoid unintended behaviour during package upgrades?  Like e.g , when the admin changed the file , does the new package fail to install as there is already a file , that is also included in the package , left on the filesystem . 

I will try that out and report tomorrow, that could make it less theoretical.

**Comment by ipwaze** [comment]
Jürgen , You were right !  
Putting a file in /etc with Your "package.install" method creates a package , that behaves like this: 
 
* on purge the config file is removed (as it should)
* in install, if the file exsists , the operating system is dealing with the "confilict" like this:  

``` bash
root@gnunitest:~# LANG=C dpkg -i /tmp/flask-demo_1.0.0_amd64.deb 
Selecting previously unselected package flask-demo.
(Reading database ... 53869 files and directories currently installed.)
Preparing to unpack .../tmp/flask-demo_1.0.0_amd64.deb ...
Unpacking flask-demo (1.0.0) ...
Setting up flask-demo (1.0.0) ...

Configuration file '/etc/default/flask-demo'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** flask-demo (Y/I/N/O/D/Z) [default=N] ? 
``` 

Thanks for that clarification!
(Especially since I first could not beleive :angel: ) 

Cheers ,
Florian
